2022-09-22 03:12:04.443 parsl:631 Rank:0 [INFO]  Python version: 3.9.7 (default, Sep 16 2021, 13:09:58) 
[GCC 7.5.0]
2022-09-22 03:12:04.444 parsl:632 Rank:0 [INFO]  Debug logging: False
2022-09-22 03:12:04.444 parsl:633 Rank:0 [INFO]  Log dir: /global/u1/m/mcarlson/LandIce/ALITune/optimize/modeling/nrun30_greenrand_00004/runinfo/000/prlm_htex
2022-09-22 03:12:04.444 parsl:634 Rank:0 [INFO]  Manager ID: 13f670ef5290
2022-09-22 03:12:04.444 parsl:635 Rank:0 [INFO]  Block ID: 0
2022-09-22 03:12:04.444 parsl:636 Rank:0 [INFO]  cores_per_worker: 1.0
2022-09-22 03:12:04.444 parsl:637 Rank:0 [INFO]  mem_per_worker: None
2022-09-22 03:12:04.444 parsl:638 Rank:0 [INFO]  task_port: 54958
2022-09-22 03:12:04.444 parsl:639 Rank:0 [INFO]  result_port: 54002
2022-09-22 03:12:04.444 parsl:640 Rank:0 [INFO]  addresses: 10.252.1.139,128.55.64.44,10.249.0.2,10.249.0.29,login35,127.0.0.1
2022-09-22 03:12:04.444 parsl:641 Rank:0 [INFO]  max_workers: 1
2022-09-22 03:12:04.444 parsl:642 Rank:0 [INFO]  poll_period: 10
2022-09-22 03:12:04.444 parsl:643 Rank:0 [INFO]  address_probe_timeout: 30
2022-09-22 03:12:04.444 parsl:644 Rank:0 [INFO]  Prefetch capacity: 0
2022-09-22 03:12:04.444 parsl:645 Rank:0 [INFO]  Heartbeat threshold: 120
2022-09-22 03:12:04.444 parsl:646 Rank:0 [INFO]  Heartbeat period: 30
2022-09-22 03:12:04.444 parsl:647 Rank:0 [INFO]  CPU affinity: none
2022-09-22 03:12:04.444 parsl:118 Rank:0 [INFO]  Manager started
2022-09-22 03:12:34.467 parsl:131 Rank:0 [ERROR]  Caught exception while trying to determine viable address to interchange
Traceback (most recent call last):
  File "/global/homes/m/mcarlson/.local/perlmutter/3.9-anaconda-2021.11/bin/process_worker_pool.py", line 123, in __init__
    raise Exception("No viable address found")
Exception: No viable address found
