2022-09-27 01:28:32.708 parsl:631 Rank:0 [INFO]  Python version: 3.9.7 (default, Sep 16 2021, 13:09:58) 
[GCC 7.5.0]
2022-09-27 01:28:32.708 parsl:632 Rank:0 [INFO]  Debug logging: False
2022-09-27 01:28:32.708 parsl:633 Rank:0 [INFO]  Log dir: /global/u1/m/mcarlson/LandIce/ALITune/optimize/modeling/nrun30_greenlhs_00004/runinfo/000/prlm_htex
2022-09-27 01:28:32.708 parsl:634 Rank:0 [INFO]  Manager ID: 114f1cd88cdd
2022-09-27 01:28:32.708 parsl:635 Rank:0 [INFO]  Block ID: 0
2022-09-27 01:28:32.708 parsl:636 Rank:0 [INFO]  cores_per_worker: 1.0
2022-09-27 01:28:32.708 parsl:637 Rank:0 [INFO]  mem_per_worker: None
2022-09-27 01:28:32.708 parsl:638 Rank:0 [INFO]  task_port: 54108
2022-09-27 01:28:32.708 parsl:639 Rank:0 [INFO]  result_port: 54884
2022-09-27 01:28:32.708 parsl:640 Rank:0 [INFO]  addresses: 128.55.64.37,127.0.0.1,10.249.0.100,login28,10.249.0.72,10.252.1.70
2022-09-27 01:28:32.708 parsl:641 Rank:0 [INFO]  max_workers: 1
2022-09-27 01:28:32.708 parsl:642 Rank:0 [INFO]  poll_period: 10
2022-09-27 01:28:32.708 parsl:643 Rank:0 [INFO]  address_probe_timeout: 30
2022-09-27 01:28:32.708 parsl:644 Rank:0 [INFO]  Prefetch capacity: 0
2022-09-27 01:28:32.708 parsl:645 Rank:0 [INFO]  Heartbeat threshold: 120
2022-09-27 01:28:32.708 parsl:646 Rank:0 [INFO]  Heartbeat period: 30
2022-09-27 01:28:32.708 parsl:647 Rank:0 [INFO]  CPU affinity: none
2022-09-27 01:28:32.708 parsl:118 Rank:0 [INFO]  Manager started
2022-09-27 01:29:02.770 parsl:131 Rank:0 [ERROR]  Caught exception while trying to determine viable address to interchange
Traceback (most recent call last):
  File "/global/homes/m/mcarlson/.local/perlmutter/3.9-anaconda-2021.11/bin/process_worker_pool.py", line 123, in __init__
    raise Exception("No viable address found")
Exception: No viable address found
